version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd typescript-lambda-project && npm ci
      - npm install -g aws-cdk
  build:
    commands:
      - cd typescript-lambda-project && cdk deploy TypeScriptLambdaStack --require-approval never
  post_build:
    commands:
      - echo Deploy completed on `date`