version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm ci
      - npm install -g aws-cdk
  pre_build:
    commands:
      - echo "Running EC2 project build..."
      - echo "Running security scans..."
      - echo "Dependency vulnerability scan..."
      - npm audit --audit-level=high --production --json > npm-audit-report.json || echo "Audit completed with findings"
      - echo "Security scans completed successfully"
      - echo "Running basic tests..."
      - npm test
  build:
    commands:
      - npm run build
      - npm run synth
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
    - 'npm-audit-report.json'
  name: typescript-ec2-artifacts

reports:
  test-reports:
    files:
      - 'coverage/lcov.info'
    file-format: 'CLOVER'